sudo: required

language: python

os: linux

env:
    global:
      - SECRET_KEY=justfortravis
      - DNS_RESOLVER_TIMEOUT=15.0
      - DNS_UPDATE_TIMEOUT=30.0
      - TEST_K="not ddns_client"
      - TEST_OPTS=""
      - COVERAGE=""

matrix:
  include:
    - python: "2.7"
      dist: trusty
      env: DJANGO=1.11 COVERAGE="coverage run -m" TEST_K="not ddns_client" TEST_OPTS="--pep8"
    - python: "3.5"
      dist: trusty
      env: DJANGO=1.11
    - python: "3.6"
      dist: trusty
      env: DJANGO=1.11
    - python: "3.7"
      dist: xenial
      env: DJANGO=2.2

install:
    - ./scripts/travis/install.sh

script: $COVERAGE py.test $TEST_OPTS -k "$TEST_K" -m "not requires_sequential"

after_success:
    - coveralls

notifications:
    email:
        recipients:
            - info@nsupdate.info
