sudo: required

language: python

os: linux

dist: trusty

python:
    - "2.7"
    - "pypy"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"

env:
    global:
      - SECRET_KEY=justfortravis
      - DNS_RESOLVER_TIMEOUT=15.0
      - DNS_UPDATE_TIMEOUT=30.0
      - TEST_K="not ddns_client"
      - TEST_OPTS=""
      - COVERAGE=""
    matrix:
      - DJANGO=1.11

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=1.11
    - python: "3.6"
      env: DJANGO=1.11
    - python: "3.6-dev"
      env: DJANGO=1.11
  include:
    - python: "2.7"
      env: DJANGO=1.11 COVERAGE="coverage run -m" TEST_K="not ddns_client" TEST_OPTS="--pep8"
    - python: "3.6"
      env: DJANGO=1.11
    - python: "3.6-dev"
      env: DJANGO=2.0

install:
    - ./scripts/travis/install.sh

script: $COVERAGE py.test $TEST_OPTS -k "$TEST_K" -m "not requires_sequential"

after_success:
    - coveralls

notifications:
    email:
        recipients:
            - info@nsupdate.info
